apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm-p4.fullname" . }}
  labels:
    {{- include "helm-p4.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "helm-p4.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "helm-p4.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          volumeMounts:
          - name: config-volume
            mountPath: /config
          - name: config-volume-2
            mountPath: /config-2  
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
      volumes:
        - name: config-volume
          configMap:
            name: "{{ .Values.essab }}-{{ .Values.name }}-{{ .Values.providername }}-{{ .Values.image.tag }}-settings"
        - name: config-volume-2
          configMap:
            name: "{{ .Values.essab }}-{{ .Values.name }}-{{ .Values.providername }}-{{ .Values.image.tag }}-settings-v201"

       
