apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-p4.fullname" . }}
  labels:
    {{- include "helm-p4.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 3535
      targetPort: http
      protocol: TCP
      name: http

    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: httpset
  selector:
    {{- include "helm-p4.selectorLabels" . | nindent 4 }}

