apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-p4.fullname" . }}-2
  labels:
    {{- include "helm-p4.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 3838
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "helm-p4.selectorLabels" . | nindent 4 }}

